### ISSUE TITLE
Firefox does not open links

### ISSUE THREAD

**Issue by anat0lius** [Digitalone1/mpv-acestream#5]
When I click on `acestream://id` type of links, Firefox does nothing, it doesn't ask me what to do, neither I see acestream listed in Preferences > Applications. 

I'm using Fedora 37 with Gnome.

I do have acesteram-engine running I have configured the plugin to listen on the right port.

**Comment by Digitalone1** [comment]
In Gnome I think you have to associate acestream protocol to mpv.

Don't know for sure how to do it, but maybe you have to add `x-scheme-handler/acestream;` to `MimeType` key in mpv desktop entry (should be placed in `/usr/share/applications/mpv.desktop`).

Anyway it's safer to do the following. Copy the link and paste it in the command line:

```
mpv acestream://content-id
```

And if you're on Wayland, since mpv does not implement indle inhibit, it's better to launch this way: 

```
gnome-session-inhibit mpv acestream://content-id
```
